### ISSUE TITLE
b_xent is not defined

### ISSUE THREAD

**Issue by jm-zh** [XingGao-cn/NEGSC#1]
您好！十分感谢您将代码开源供我们学习。
我有幸读到了您的文章，并尝试复现您的工作以加深理解学习。我遇到了以下编译错误：
1、在class Genetation中提示GATConv is not defined。我通过from dgl.nn.pytorch import GATConv来解决。
2、在class Model中def sub_loss_batch方法提示b_xent is not defined。我尝试将b_xen定义为b_xent = nn.BCEWithLogitsLoss()。
感谢您能查看我的问题，期待您的回复。谢谢！

**Comment by XingGao-cn** [comment]
您好，我们的稿件正在外审中，为了解决审稿人的关切我们将在审稿结束后上传改稿后的完整代码。

**Comment by XingGao-cn** [comment]
对于您提及的问题，可以先尝试使用以下仓库中的代码：https://github.com/renj-xu/NEGSC。需要说明的是，这不是我们文章的最终版本，对于后续问题，请留言。

**Comment by XingGao-cn** [comment]
对于您提及的问题，可以先尝试使用以下仓库中的代码：[NEGSC](https://github.com/renj-xu/NEGSC)。需要说明的是，这不是我们文章的最终版本，对于后续问题，请留言。

**Comment by jm-zh** [comment]
好的，感谢您的回复，期待您的作品发表。
